INSERT INTO Lands(name, description)
VALUES  ('Land A', 'A rich and fertile land'),
        ('Land B', 'A rich and fertile land'),
        ('Land C', 'A rich and fertile land'),
        ('Land D', 'A rich and fertile land'),
        ('Land E', 'A rich and fertile land'),
        ('Land F', 'A rich and fertile land'),
        ('Land G', 'A rich and fertile land'),
        ('Land H', 'A rich and fertile land'),
        ('Land I', 'A rich and fertile land'),
        ('Land J', 'A rich and fertile land'),
        ('Land K', 'A rich and fertile land'),
        ('Land L', 'A rich and fertile land'),
        ('Land M', 'A rich and fertile land'),
        ('Land N', 'A rich and fertile land'),
        ('Land O', 'A rich and fertile land'),
        ('Land P', 'A rich and fertile land'),
        ('Land Q', 'A rich and fertile land'),
        ('Land R', 'A rich and fertile land'),
        ('Land S', 'A rich and fertile land'),
        ('Land T', 'A rich and fertile land'),
        ('Land U', 'A rich and fertile land'),
        ('Land V', 'A rich and fertile land'),
        ('Land W', 'A rich and fertile land'),
        ('Land X', 'A rich and fertile land'),
        ('Land Y', 'A rich and fertile land'),
        ('Land Z', 'A rich and fertile land'),
        ('Land 0', 'A rich and fertile land'),
        ('Land 1', 'A rich and fertile land'),
        ('Land 2', 'A rich and fertile land'),
        ('Land 3', 'A rich and fertile land'),
        ('Land 4', 'A rich and fertile land'),
        ('Land 5', 'A rich and fertile land'),
        ('Land 6', 'A rich and fertile land'),
        ('Land 7', 'A rich and fertile land'),
        ('Land 8', 'A rich and fertile land'),
        ('Land 9', 'A rich and fertile land'),
        ('Racoon Castle', 'The castle of Sebubu, in impregnable fortress defended by huge 6 feet tall raccoons.');

INSERT INTO Modifiers(name, description, attack, defense, capped)
VALUES ('Crowns of Raccoons', 'A crown passed down by the ancient racoon gods to the King.', 999, 999, 'False'),
       ('Grond, Hammer of the Underworld', 'A great warhammer', 0.05, 0, 'True'),
       ('Ancient Blade', 'The ancient blade of Ner\' Zul, has a strong defensive aura', 0, 0.02, 'True'),
       ('Shield of the Gods', 'A golden shield blessed by the gods', 0, 0.07);
